initScope: "@samantha-uk"

npmPublishAccess: public

packageExtensions:
  eslint-config-airbnb-typescript@*:
    dependencies:
      eslint: latest
      eslint-plugin-import: latest
      eslint-plugin-jsx-a11y: latest
      eslint-plugin-react: latest
      eslint-plugin-react-hooks: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
